name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: <49b7623f102e38eaac56bcbf663edeedc76b703be476df4fe4507d09bb068315>
        with:
          coverageCommand: npm run coverage
          debug: true